---
linters-settings:
  gocyclo:
    min-complexity: 42
  cyclop:
    max-complexity: 42
  gocognit:
    min-complexity: 42
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 3

linters:
  enable-all: true
  disable:
    - nlreturn
    - wsl
    - wrapcheck
    - gomnd
    - varnamelen
    - musttag
    - ireturn
    - exhaustruct
    - gochecknoglobals
    - lll
    - nestif
    - testpackage
    - paralleltest
    - mnd
    - tagliatelle
    - depguard
    - execinquery # deprecated
    - exportloopref # deprecated

issues:
  exclude:
    - "use of `fmt.Println` forbidden by pattern"
