#https://taskfile.dev/
version: '3'

includes:
  tools:
    taskfile: taskfile-tools.yml
    flatten: true
  ci:
    taskfile: taskfile-ci.yml
    flatten: true
  go:
    taskfile: taskfile-go.yml
    flatten: true
    internal: true
  external:
    taskfile: taskfile-external.yml
    flatten: true

env:
  TMP: tmp

tasks:

  generate:
    desc: 'generate the project documentation/README'
    cmds:
      - cat doc/README-start.md > README.md
      - go run . --help >> README.md
      - cat doc/README-end.md >> README.md

  ci:
    desc: 'do all the checks'
    deps:
      - task: check-yq-installed
    cmds:
      - task: tidy
      - task: format
      - task: licenses
      - task: generate
      - task: lint
      - task: test
      - task: govulncheck

  test:
    desc: 'run Go tests'
    deps:
      - task: check-go-tool
        vars:
          TOOL: GOTESTSUM
    cmds:
      - CGO_ENABLED=1 /{{.TMP}}/gotestsum/{{.GOTESTSUM_VERSION}}/gotestsum --hide-summary=output --format-icons=hivis --format=testdox --format-hide-empty-pkg -- -race ./...

  install:
    desc: 'build the project'
    cmds:
      - go build -buildvcs=true
      - go install

  run:
    desc: 'run the project'
    cmds:
      - go run .

  update-x:
    desc: 'update golang.org/x/ dependencies'
    cmds:
      - go get -u golang.org/x/...
      - task: tidy

  tools-install:
    task:
      - task: check-go-tools
        vars:
          TOOLS: [YQ, BETTERALIGN, STATICCHECK, GOLICENSES, GOVULNCHECK, GOFUMPT, REVIVE, GOTESTSUM]
